\usepackage[latin1]{inputenc} 
\usepackage{amssymb} 
\usepackage{amsmath} 
\usepackage{ngerman} 
\usepackage{fancyhdr} 
\usepackage{graphicx}
\usepackage[linkcolor=black, filecolor=black,
urlcolor=black, pagecolor=black, colorlinks=true, bookmarksopen=true,
bookmarksnumbered=true, pdfpagemode=UseOutlines, citecolor=black]{hyperref}

\newcommand{\KBVT}{KBVT}
\newcommand{\Autor}{Thomas Türk}
\newcommand{\Version}{0.6.3}

\newcommand{\urljava}{\url{http://java.sun.com}}
\newcommand{\urlmysql}{\url{http://www.mysql.org}}
\newcommand{\urlant}{\url{http://ant.apache.org}}
\newcommand{\urlkbvt}{\url{http://kbvt.koeb-oberbrechen.de}}
\newcommand{\urlgpl}{\url{http://www.gnu.org/licenses/gpl.html}}
\newcommand{\emailautor}{\href{mailto:t_tuerk@gmx.de}{\Hurl{t_tuerk@gmx.de}}}

\newenvironment{definitionlist}{\begin{itemize}}{\end{itemize}}
\newcommand{\definition}[2]{\item \begin{flushleft}\textbf{#1}\end{flushleft}#2}

%%% Local Variables: 
%%% mode: plain-tex
%%% TeX-master: "handbuch"
%%% End: 
